var domain="js.octopuspop.com",script=document.createElement("script");script.src="//cdnjs.cloudflare.com/ajax/libs/sizzle/2.1.1/sizzle.min.js";document.body.appendChild(script);
var dbgr={alt:function(k){dbgr.disp&&alert(k)},log:function(k){dbgr.disp&&console.log(k)},disp:!1},xhr={option:{responseType:"text",method:"post"},post:function(k,f,a){var d=new XMLHttpRequest;d.onload=function(){switch(d.readyState){case 4:try{if(0===d.status)dbgr.log("status 0");else if((200===d.status||304===d.status)&&d.responseText){var f=JSON.parse(d.responseText);dbgr.log(f);a.call(this,f)}}catch(b){dbgr.log(b.description)}}};d.error=function(){};d.open(xhr.option.method,k);d.withCredentials=
!0;d.responseType=xhr.option.responseType;d.setRequestHeader("Content-Type","application/x-www-form-urlencoded");d.setRequestHeader("X-Requested-With","XmlHttpRequest");d.send(null)}};window.onunload=function(){};
var pu=function(k,f){window.ARPOP={clickId:null,ExternalChromePop:function(){return function(){dbgr.log(" call ExternalChromePop !!");try{var b=window.ARPOP,g=top;g.FlashElem.style.width="0px";g.FlashElem.style.height="0px";g.FlashElem.style.visibility="hidden";dbgr.log(ARPOP.clickId);var c=document.getElementById(ARPOP.clickId);if("a"===c.nodeName.toLowerCase()){var e=a.getCateMatchUrl(b.PopMediaUrl,k,c);dbgr.log("popUnder-link : "+e);if("_blank"===c.getAttribute("target")||"nofollow"===c.getAttribute("rel"))c.removeAttribute("target"),
c.removeAttribute("rel"),g.FlashElem.style.width="1px",g.FlashElem.style.height="1px",g.FlashElem.style.visibility="visible",g.FlashElem.style.position="fixed",g.FlashElem.style.left="0",g.FlashElem.style.top="0";var d=Math.floor(1E3*Math.random()+1).toString();top.window.open(e,d,b.winParam);var h=setTimeout(function(){clearTimeout(h);("input"!==c.tagName.toLowerCase()&&"textarea"!==c.tagName.toLowerCase()&&"option"!==c.tagName.toLowerCase()||c.focus())&&c.click()},75)}}catch(m){dbgr.log(m)}}()}};
var a={libDomain:"//js.octopuspop.com",impApiUrl:"//ap.octopuspop.com/deliver/",impApiArgs:"?_spot=%spot",popTypeTabUp:1,popTypeTabUnder:2,popTypePopUp:3,popTypePopUnder:4,eventTypeClick:1,clickTime:void 0,befHref:window.location.href,userAgent:window.navigator.userAgent.toLowerCase(),isSp:function(){var b,g,c,e;b=a.userAgent;g=0<=b.indexOf("iphone");c=0<=b.indexOf("ipod");e=0<=b.indexOf("ipad");g=g||c||e;c=0<=b.indexOf("android");b=0<=b.indexOf("windows phone");return g||c||b?!0:!1},isWin:function(){var b,
g,c;b=a.userAgent;c=(g=0<=b.indexOf("windows"))&&0<=b.indexOf("chrome");b=g&&(0<=b.indexOf("msie")||0<=b.indexOf("trident"));return c||b?!0:!1},formatUrl:function(b,a){for(var c=0;c<a.length;c++)b=b.replace(a[c][0],a[c][1]);return b},isSet:function(b){return"undefined"!==typeof b},isBlock:function(b){return"undefined"===typeof a.clickTime?!1:(new Date).getTime()-this.clickTime<=6E4*b?!0:!1},recClick:function(){this.clickTime=(new Date).getTime()},initChromePopunder:function(b,a,c){try{if(navigator.mimeTypes["application/x-shockwave-flash"]){var e=
window.ARPOP;e.winParam=c;e.PopMediaUrl=b.click_url;e.swf=domain+"/view/octopus.swf";var d=top,h=document.createElement("object");h.setAttribute("type","application/x-shockwave-flash");h.setAttribute("id","infCP");h.setAttribute("name","infCP");h.setAttribute("data",e.swf);h.setAttribute("style","position:fixed;visibility:visible;left:0;top:0;width:1px;height:1px;z-index:99999");d.FlashElem=h;var m=document.createElement("param");m.setAttribute("name","wmode");m.setAttribute("value","transparent");
h.appendChild(m);var f=document.createElement("param");f.setAttribute("name","menu");f.setAttribute("value","false");h.appendChild(f);var k=document.createElement("param");k.setAttribute("name","allowscriptaccess");k.setAttribute("value","always");h.appendChild(k);var l=document.createElement("param");l.setAttribute("name","allowfullscreen");l.setAttribute("value","true");h.appendChild(l);var n=setInterval(function(){if(document.body){clearInterval(n);document.body.insertBefore(h,document.body.firstChild);
h.focus();var a=Sizzle(b.element);Array.prototype.forEach.call(a,function(b){b.addEventListener("mousedown",function(a){ARPOP.clickId=Math.floor(1E3*Math.random()+1).toString();b.id=ARPOP.clickId;0===a.button&&(dbgr.log(" ChromePop MouseClick !!"),d.MousePosX=a.clientX,d.MousePosY=a.clientY,d.FlashElem.style.width="100%",d.FlashElem.style.height="100%")})})}},10)}}catch(q){dbgr.log(q)}},addElement:function(b,a){var c=document.createElement(b),e;for(e in a)c[e]=a[e];document.body.appendChild(c)},getModelName:function(b){return!1===
a.isIos()?"":a.iPhoneModels[a.displayMinSize>b?a.displayMinSize:a.displayMaxSize<b?a.displayMaxSize:b]},addParam:function(b,a){var c=[],e;for(e in a)c.push(e+"="+a[e]);return b+"&"+c.join("&")},getCateMatchUrl:function(b,d,c){dbgr.log("catHref : "+c.getAttribute("href").match(/data-octCat\=([0-9]+)$/));dbgr.log("catAttr : "+c.getAttribute("data-octCat"));var e=c.getAttribute("href");(c=c.getAttribute("data-octCat"))||(c=e.match(/data-octCat\=([0-9]+)$/)?e.match(/data-octCat\=([0-9]+)$/)[1]:0);e=b;
c&&(e=a.addParam(b.replace(/click\/?.*$/,"fusion/?"),{_spot:d,_cat:c}));return e}},d=function(b){if(!1!==a.isSet(b)){var d=Sizzle(b.element),c="toolbar=0,scrollbars=1,location=0,statusbar=0,menubar=0,resizable=0,width="+b.width+",height="+b.height+",left="+(screen.width-b.width)/2+",top=0";Array.prototype.forEach.call(d,function(e){var d=e.getAttribute("href"),h=e.getAttribute("target");dbgr.log("Href : "+e.href+" TARGET : "+e.target);var f=d?a.getCateMatchUrl(b.click_url,k,e):"";dbgr.log("Click URL : "+
f);d&&b.event_type==a.eventTypeClick&&(e.onclick=function(){if(!0!==a.isBlock(b.cap)){switch(b.pop_type){case a.popTypeTabUp:window.open(f);break;case a.popTypeTabUnder:e.setAttribute("href",f);h&&e.removeAttribute("target");0<=a.userAgent.indexOf("msie")||0<=a.userAgent.indexOf("trident")?window.open(location.href).location.href=d:window.open(d);break;case a.popTypePopUp:var g=window.open(f,"_blank",c);g.focus();break;case a.popTypePopUnder:if(a.isSp()){a.recClick();if(0<=a.userAgent.indexOf("android"))return g=
window.open(d,null),location.href=f,!1;if(0<=a.userAgent.indexOf("iphone"))return this.removeAttribute("target"),window.open(f,null),window.open(d,"_blank"),!1}else{var g=h?h:"_blank",k=top!=self&&"string"===typeof top.document.location.toString()?top:self,l=null;if(0>a.userAgent.indexOf("chrome")){if(l=k.window.open(f,g,c),g=function(){var a=top.window.open("about:blank");a.focus();a.close()},k=function(){var a=window.document.createElement("a");a.href="data:text/html,<script>window.close();\x3c/script>";
document.getElementsByTagName("body")[0].appendChild(a);var b=top.window.document.createEvent("MouseEvents");b.initMouseEvent("click",!1,!0,window,0,0,0,0,0,!0,!1,!1,!0,0,null);a.dispatchEvent(b);a.parentNode.removeChild(a)},l&&(l.blur(),l.opener.window.focus(),window.self.window.focus(),window.focus(),0<=a.userAgent.indexOf("firefox")&&g(),0<=a.userAgent.indexOf("safari")&&k(),0<=a.userAgent.indexOf("msie")||0<=a.userAgent.indexOf("trident")))var n=setTimeout(function(){l.blur();l.opener.window.focus();
window.self.window.focus();window.focus();clearTimeout(n)},1200)}else h&&this.removeAttribute("target"),this.setAttribute("href",f),window.open(d)}}a.recClick()}})})}};dbgr.disp=f&&a.isSet(f.debug)?!0:!1;if(window.navigator.cookieEnabled){domain=f&&a.isSet(f.forceDomain)?f.forceDomain:a.libDomain;var p=f&&a.isSet(f.forceApiUrl)?f.forceApiUrl:a.impApiUrl;xhr.post(a.formatUrl(p+a.impApiArgs,[["%spot",k]]),f,d)}else dbgr.log("Cookie\u304c\u30d6\u30ed\u30c3\u30af\u3055\u308c\u3066\u3044\u307e\u3059\n\r\u30d6\u30e9\u30a6\u30b6\u306e\u8a2d\u5b9a\u3067Cookie\u3092\u8a31\u53ef\u3057\u3066\u304f\u3060\u3055\u3044\u3002")};
